//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSICOVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Compras()
        {
            this.tb_DetalleCompras = new HashSet<tb_DetalleCompras>();
        }
    
        public int IdCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public int NumFac { get; set; }
        public string DetalleCompra { get; set; }
        public decimal TotalCompra { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual tb_Empleados tb_Empleados { get; set; }
        public virtual tb_FormaPago tb_FormaPago { get; set; }
        public virtual tb_Proveedores tb_Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DetalleCompras> tb_DetalleCompras { get; set; }
    }
}
