//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSICOVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Inventarios
    {
        public int IdInventario { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public int Existencia { get; set; }
    
        public virtual tb_Productos tb_Productos { get; set; }
    }
}
