//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSICOVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Productos()
        {
            this.tb_DetalleCompras = new HashSet<tb_DetalleCompras>();
            this.tb_DetalleVentas = new HashSet<tb_DetalleVentas>();
            this.tb_Inventarios = new HashSet<tb_Inventarios>();
        }
    
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> IdCategoria { get; set; }
    
        public virtual tb_Categorias tb_Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DetalleCompras> tb_DetalleCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DetalleVentas> tb_DetalleVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Inventarios> tb_Inventarios { get; set; }
    }
}
