//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSICOVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuarios
    {
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    
        public virtual tb_Empleados tb_Empleados { get; set; }
        public virtual tb_Roles tb_Roles { get; set; }
    }
}
