//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSICOVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Ventas()
        {
            this.tb_DetalleVentas = new HashSet<tb_DetalleVentas>();
        }
    
        public int IdVenta { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public int NumFac { get; set; }
        public string Detalle { get; set; }
        public decimal TotalVenta { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual tb_Clientes tb_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DetalleVentas> tb_DetalleVentas { get; set; }
        public virtual tb_Empleados tb_Empleados { get; set; }
        public virtual tb_FormaPago tb_FormaPago { get; set; }
    }
}
